language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
  - TOX_ENV=flake8
install: pip install tox
script: 
  - tox -e $TOX_ENV
services: 
  - mongodb
  - redis-server
before_script:
  - export PATH=/opt/python/2.7.6/bin:/opt/python/2.6.9/bin:/opt/python/3.4.0/bin:/opt/python/3.3.5/bin:/opt/python/3.2.5/bin:/opt/python/pypy-2.2.1/bin:$PATH
  - sleep 15
  - mongo eve_test --eval 'db.addUser("test_user", "test_pw");'
    #- travis_retry mongo eve_test --eval 'db.addUser(test_user, "test_pw");'
branches:
  only:
    - master
    - develop
