language: python
python:
  - "2.7"
  - "2.6"
install: pip install --exclude="tests" flake8
script: 
  - flake8 eve
  - python setup.py test
services: mongodb
before_script:
  - mongo eve_test --eval 'db.addUser("test_user", "test_pw");'

branches:
  only:
    - master
    - develop
